version: '3'

services:
  reverse-proxy:
    image: traefik:v1.7.12-alpine #The official Traefik docker image
    container_name: traefik
    # command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    networks:
      - traefik-web
    ports:
      - "80:80"     #The HTTP port
      - "8080:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml
    labels:
      - traefik.frontend.rule=Host:monitor.local.com
      - traefik.port=8080

networks:
  traefik-web:
    external: true
