version: '3'

networks:
  traefik-web:
    external: true

services:
  nginx-1:
    # 使用 Nginx 綁定一個 Host
    image: nginx:alpine
    volumes:
      - ./host01:/usr/share/nginx/html:ro
    labels:
      - traefik.backend=nginx-1
      - traefik.frontend.rule=Host:web.local.com
      - traefik.docker.network=traefik-web
      - traefik.port=80
    networks:
      - traefik-web
  nginx-2:
    # 使用 Nginx 綁定另一個 Host
    image: nginx:alpine
    volumes:
      - ./host02:/usr/share/nginx/html:ro
    labels:
      - traefik.backend=nginx-2
      - traefik.frontend.rule=Host:web2.local.com
      - traefik.docker.network=traefik-web
      - traefik.port=80
    networks:
      - traefik-web
  nginx-2-lb:
    # 使用 Nginx 綁定另一個 Host
    image: nginx:alpine
    volumes:
      - ./host02:/usr/share/nginx/html:ro
    labels:
      - traefik.backend=nginx-2
      - traefik.frontend.rule=Host:web2.local.com
      - traefik.docker.network=traefik-web
      - traefik.weight=10
      - traefik.port=80
    networks:
      - traefik-web
  whoami-1:
    # 測試 whoami 綁定另一個 Host
    image: emilevauge/whoami:latest
    labels:
      - traefik.backend=whoami-1
      - traefik.frontend.rule=Host:whoami.local.com
      - traefik.docker.network=traefik-web
      - traefik.port=80
    networks:
      - traefik-web
    command: sleep infinity
  whoami-2:
    # 測試 whoami 綁定相同 Host 的不同路徑
    image: emilevauge/whoami:latest
    labels:
      - traefik.backend=whoami-2
      - traefik.frontend.rule=Host:whoami.local.com;PathPrefixStrip:/web
      - traefik.docker.network=traefik-web
      - traefik.weight=1
      - traefik.port=80
    networks:
      - traefik-web
    command: sleep infinity
  whoami-2-lb:
    # 測試 whoami 綁定相同 Host 的不同路徑
    image: emilevauge/whoami:latest
    labels:
      - traefik.backend=whoami-2
      - traefik.frontend.rule=Host:whoami.local.com;PathPrefixStrip:/web
      - traefik.docker.network=traefik-web
      - traefik.weight=10
      - traefik.port=80
    networks:
      - traefik-web
    command: sleep infinity
